# download file
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)

# Read data, convert into date format and extract relevant data
dataset <- read.table(unz(temp, "household_power_consumption.txt"), sep = ";", na.strings = "?", header = TRUE)
dataset$datetime <- strptime(paste(dataset$Date, dataset$Time), format = "%d/%m/%Y %H:%M:%S")
dataset$Date <- as.Date(dataset$Date, format = "%d/%m/%Y")
datasetSub <- subset(dataset, dataset$Date >= as.Date("2007-02-01") & dataset$Date <= as.Date("2007-02-02"))

png(filename = "Plot4.png", width = 480, height = 480)
par(mfrow = c(2,2), mar = c(4,4,2,2))
# Plot (1,1)
plot(datasetSub$datetime, datasetSub$Global_active_power, ylab = "Global Active Power (kilowatts)", xlab = "", type = 'l')
# Plot (1,2)
with(datasetSub, plot(datetime, Voltage, type = 'l'))
# Plot (2,1)
plot(datasetSub$datetime, datasetSub$Sub_metering_1, ylab = "Energy sub metering", xlab = "", type = 'n')
points(datasetSub$datetime, datasetSub$Sub_metering_1, type = "l")
points(datasetSub$datetime, datasetSub$Sub_metering_2, type = "l", col = "red")
points(datasetSub$datetime, datasetSub$Sub_metering_3, type = "l", col = "blue")
legend ("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, bty = 'n')
# Plot (2,2)
with(datasetSub, plot(datetime, Global_reactive_power, type = 'l'))
dev.off()